In [1]:
import numpy as np
import pandas as pd 
%matplotlib inline 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [2]:
df = pd.read_csv("counties.csv")
df.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1       0
1  2020-01-22  Snohomish  Washington  53061.0      1       0
2  2020-01-23  Snohomish  Washington  53061.0      1       0
3  2020-01-24       Cook    Illinois  17031.0      1       0
4  2020-01-24  Snohomish  Washington  53061.0      1       0

In [3]:
total = df.groupby(['date'], axis=0,as_index=False).sum()
total['date'] = pd.to_datetime(total['date'], format='%Y-%m-%d')
total['Day of Year 2020']=total['date'].dt.dayofyear
total_days = total.groupby(['Day of Year 2020'], axis=0).sum()
total_days

                        fips   cases  deaths
Day of Year 2020
21                   53061.0       1       0
22                   53061.0       1       0
23                   53061.0       1       0
24                   70092.0       2       0
25                   76151.0       3       0
...                      ...     ...     ...
95                70752270.0  310842    8505
96                71835852.0  336410    9661
97                73133230.0  366362   11709
98                74975534.0  397752   12959
99                75907246.0  429283   14803

[79 rows x 3 columns]

In [6]:

for day in range (2,total_days.shape[0]):
    total_days[['cases','deaths']].iloc[:day].plot(marker='x', logy=True, grid=True, xlim=[21,90])
    plt.savefig("images/"+str(day).zfill(4)+".png")
    plt.close()

https://askubuntu.com/questions/610903/how-can-i-create-a-video-file-from-a-set-of-jpg-images

In [ ]:
!cd images && ffmpeg -framerate 25 -i %04d.png -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p output.mp4

ffmpeg version 4.1.4-1build2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, image2, from '%04d.png':
  Duration: 00:00:03.08, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 432x288 [SAR 2834:2834 DAR 3:2], 25 fps, 25 tbr, 25 tbn, 25 tbc
File 'output.mp4' already exists. Overwrite ? [y/N]